### ISSUE TITLE
Module must be signed to be installed on Firefox 

### ISSUE THREAD

**Issue by fabioballi** [robamler/dontprint#33]
https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by robamler** [comment]
Thanks for reporting! I moved from Firefox to Chrome on my own machine and lost track of changes in the Add-on signing policy at Mozilla. I now have a "preliminarily" signed .xpi for Dontprint (not sure what this means exactly, i.e. if Mozilla can still revoke this). I tested it successfully in Firefox on Linux, but could you please check if it works on your machine as well, just to be sure?

* If you have already installed Dontprint (in which case it has probably been deactivated): Type "about:addons" in the addressbar, right-click on "Dontprint" and then select "Search for updates". Firefox should download version 1.1.1 of Dontprint and once you restart your browser the warning that the Add-on could not be verified should disappear.
* If haven't yet been able to install Dontprint, please go to http://dontprint.net/download/. There should be a prompt that allows you to install Dontprint version 1.1.1.

I would appreciate if you could briefly respond whether or not this worked.

**Comment by fabioballi** [comment]
Hi. Thanks for the prompt fix. In fact I found how to deactivate the verification in Firefox settings, which enabled me to load it. There was then a warning in the plugins page saying it was not verified. A few days ago, this warning disappeared, so I suppose it just updated and found the signature. :)

**Comment by robamler** [comment]
Thanks.
