### ISSUE TITLE
Allow for larger font sizes

### ISSUE THREAD

**Issue by colegleason** [robamler/dontprint#37]
I currently read at the max Dontprint allows (130%) but would love to use 150-200% if allowed. One reason I love reading on my Kindle is that I never have to buy large print books, and the reason I use Dontprint is because I can't stand to read 10-pt font on paper!

**Comment by robamler** [comment]
I can add this to the next version. Until then, you can get a larger zoom factor as follows: Open the Dontprint settings and click on "Device". There's a box where you can input the screen resolution ("pixels per inch") of your e-reader. If you put a larger number here, k2pdfopt will make everything larger in the output file. In fact, this is exactly what happens internally when you pick a zoom factor other than 100%.

Changing the pixels-per-inch value in the Dontprint settings will change the font size for _all_ articles. If you want to print just some papers with a high zoom factor, check the option "Add additional command-line parameters to k2pdfopt" on the cropping tab and add the following text in the box below: `-odpi <number>` (where you should replace `<number>` by the pixels-per-inch value that you want to use for this article.)

**Comment by colegleason** [comment]
Awesome, thanks for the detailed guide!
